---

- name: Filebeat template file(s)
  copy:
    src: "{{ item }}"
    dest:  "{{ filebeat_config_file | dirname }}/{{ item | basename }}"
    owner: "{{ filebeat_user }}"
    group: "{{ filebeat_group }}"
    mode: 0640
  with_items: "{{ filebeat_templates }}"
  notify: filebeat restart

# vi:ts=2:sw=2:et:ft=yaml
